/* main.svelte generated by Svelte v3.50.1 */
"use strict";

const { SvelteComponent: SvelteComponent$, detach: detach$, element: element$, init: init$, insert: insert$, noop: noop$, safe_not_equal: safe_not_equal$ } = require("/Users/blazejnowakowski/Projects/svelte/internal");

function create_fragment(ctx) {
	let h1$;

	return {
		c() {
			h1$ = element$("h1");
			h1$.textContent = "Hello!";
		},
		m(target, anchor) {
			insert$(target, h1$, anchor);
		},
		p: noop$,
		i: noop$,
		o: noop$,
		d(detaching) {
			if (detaching) detach$(h1$);
		}
	};
}

class Main$ extends SvelteComponent$ {
	constructor(options) {
		super();
		init$(this, options, null, create_fragment, safe_not_equal$, {});
	}
}

exports.default = Main$;